// src/app/config/env.ts
import {
  AWS_REGION,
  COGNITO_USER_POOL_ID,
  COGNITO_CLIENT_ID,
  AUTH_PROVIDER,
  DASHBOARD_PROVIDER,
  BOOKING_PROVIDER,
  PETS_PROVIDER,
  API_BASE_URL,
} from '@env';

export const ENV = {
  AWS_REGION,
  COGNITO_USER_POOL_ID,
  COGNITO_CLIENT_ID,
  AUTH_PROVIDER,
  DASHBOARD_PROVIDER,
  BOOKING_PROVIDER,
  PETS_PROVIDER,
  API_BASE_URL,
};

